name: Build
on:
  pull_request:
    branches:
    - main
    paths:
    - '.github/workflows/build.yml'
    - 'index.bs'
    - 'ts/**'
  push:
    branches:
    - main
    paths:
    - '.github/workflows/build.yml'
    - 'index.bs'
    - 'ts/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: mkdir out
      - name: Build Spec
        uses: w3c/spec-prod@v2
        with:
          DESTINATION: out
          VALIDATE_MARKUP: false
      - uses: actions/setup-node@v3
      - name: Build Validator
        run: |
          npm ci --prefix ./ts
          npm run pack --prefix ./ts
      - name: Assemble
        run: |
          ls ./out
          mv ./ts/dist/header-validator/main.js ./out/validate-headers.js
          mv ./ts/src/header-validator/index.html ./out/validate-headers.html
      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: './out'

  deploy:
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
